[package]
name = "whiskers-launcher-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
dirs = "5.0.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tux-icons = {version = "0.2.2", optional = true}
walkdir = "2.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop-desktop-entry = "0.5.0"
tux-icons = "0.2.2"

[target.'cfg(target_os = "windows")'.dependencies]
lnk = "0.5.1"
powershell_script = "1.1.0"

[features]
core-api = ["dep:tux-icons"]
extensions-api = []
all = ["core-api", "extensions-api"]
